//label for the dropdown
export const language = [
    { code: "USD" },
    { code: "AUD" },
    { code: "BRL" },
    { code: "CAD" },
    { code: "CHF" },
    { code: "CLP" },
    { code: "CNY" },
    { code: "DKK" },
    { code: "EUR" },
    { code: "GBP" },
    { code: "HKD" },
    { code: "INR" },
    { code: "ISK" },
    { code: "JPY" },
    { code: "KRW" },
    { code: "NZD" },
    { code: "PLN" },
    { code: "RUB" },
    { code: "SEK" },
    { code: "SGD" },
    { code: "THB" },
    { code: "TRY" },
    { code: "TWD" },
]

